function myExportToPPTX(params)
% requires exportToPPTX github repo

% change fig background color to white
params.fig.Color = 'w';

% make figure directory if it doesn't exist
if ~exist(params.figPath,'dir')
    mkdir(params.figPath)
end

%% check if presentation already exists

pth = fullfile(params.figPath,params.filename);

exists = exist([pth '_v1.pptx'],'file'); % check if an initial verion exists

if exists
    % find latest version
    fns = patternMatchCellArray({dir(params.figPath).name}',{params.filename},'all');
    fns = natsortfiles(fns);
    fn = fns{end}; % this is the latest version filename
    x = strsplit(fn,{'_','.'});
    v = x{end-1}; % 'vXX';
    x = strsplit(v,'v');
    v = x{end};
    newpth = [pth '_v' v];
else
    newpth = [pth '_v1'];
end


if exist([newpth '.pptx'],'file') && ~params.newVersion
    % Open existing presentation
    pptx = exportToPPTX(newpth);
else
    if exist([newpth '.pptx'],'file') && params.newVersion
        % increment version
        newpth = [pth '_v' num2str(str2double(v)+1)];
    end
    % Start new presentation
    pptx    = exportToPPTX('', ...
        'Dimensions',[12 6], ...
        'Title','Example Presentation', ...
        'Author','MATLAB', ...
        'Subject','Automatically generated PPTX file', ...
        'Comments','This file has been automatically generated by exportToPPTX');

    % Another way of setting some properties
    pptx.title          = 'Demonstration Presentation';
    pptx.author         = 'exportToPPTX Example';
    pptx.subject        = 'Demonstration of various exportToPPTX commands';
    pptx.description    = 'Description goes in here';

    % Additionally background color for all slides can be set as follows:
    % exportToPPTX('new','BackgroundColor',[0.5 0.5 0.5]);
end


%% Add fig to slide

slideId = pptx.addSlide();
pptx.addPicture(params.fig);
pptx.addTextbox(params.slideTitle);


%% Save presentation and close presentation -- overwrite file if it already exists
% Filename automatically checked for proper extension
newFile = pptx.save(newpth);

end

